//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phonebook.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class phonenumber
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Required First Name")]
        public string first_name { get; set; }

        [Required(ErrorMessage = "Required Last Name")]
        public string last_name { get; set; }

        [Required(ErrorMessage = "Required Phone Name")]
        [MinLength(10,ErrorMessage ="Phone Number Needs to be of 10 digits")]
        [MaxLength(10,ErrorMessage = "Phone Number Needs to be of 10 digits")]
        public string phone_number { get; set; }
    }
}
